#!/bin/sh
# build the webassembly module and the wordlist bundle for the browser demo
# needs emscripten (emcc) on the path
# outputs are self contained so web/index.html opens straight from file://
#
#   web/emojiseed.js   wasm inlined as base64 via SINGLE_FILE
#   web/wordlist.js    the 4096 emojis as a javascript array
#
# run from the repo root or via  make wasm

set -eu

here=$(dirname "$0")
root=$(cd "$here/.." && pwd)
cd "$root"

# arch installs emcc outside the default path so add it if needed
if ! command -v emcc >/dev/null 2>&1 && [ -x /usr/lib/emscripten/emcc ]; then
    PATH="$PATH:/usr/lib/emscripten"
fi

if ! command -v emcc >/dev/null 2>&1; then
    echo "error emcc not found install emscripten first" >&2
    echo "  arch:   sudo pacman -S emscripten" >&2
    echo "  others: https://emscripten.org/docs/getting_started/downloads.html" >&2
    exit 1
fi

echo "generating web/wordlist.js from data/emojis.txt"
{
    printf '// generated by web/build.sh do not edit\n'
    printf 'const EMOJISEED_WORDS = [\n'
    # one quoted emoji per line comma separated
    sed 's/\r$//' data/emojis.txt | awk 'NF { printf "  \"%s\",\n", $0 }'
    printf '];\n'
} > web/wordlist.js

count=$(grep -c '"' web/wordlist.js || true)
echo "  wrote $count emojis"

echo "compiling wasm with emcc"
emcc web/emojiseed_wasm.c src/core.c src/sha256.c \
    -O3 \
    -sEXPORTED_FUNCTIONS=_es_encode,_es_decode,_malloc,_free \
    -sEXPORTED_RUNTIME_METHODS=cwrap,HEAPU8,HEAP32 \
    -sMODULARIZE=1 \
    -sEXPORT_NAME=EmojiseedModule \
    -sSINGLE_FILE=1 \
    -sENVIRONMENT=web \
    -sALLOW_MEMORY_GROWTH=1 \
    -o web/emojiseed.js

echo "done open web/index.html in a browser"
